### ISSUE TITLE
Memory Leaks in GraylogTarget

### ISSUE THREAD

**Issue by SergeyKulgan** [NLog/NLog.Targets.Network#11]
Hi guys,
There is memory leak problem in NLog. 
We started using new target - Graylog, that implements TargetWithContext.
Our most loaded application sends about 200-400 messages per second and, with enabled Graylog target, its memory consumption constantly grow up to almost max available value for the app - 7 GB.
This app service hosted on Azure.  Please see "Average memory working set" metric dynamics:
![image](https://user-images.githubusercontent.com/16491966/75153635-8c1e9b80-5714-11ea-90d0-c9d63cf9335e.png)
One of spikes (that corresponding to collected memory dump):
![image](https://user-images.githubusercontent.com/16491966/75170626-1118ad80-5733-11ea-8735-c093dacaea9e.png)

Then we collected memory dump of our service with Graylog target enabled.
Here also please see selection from analysis report for this dump:
![image](https://user-images.githubusercontent.com/16491966/75153946-41515380-5715-11ea-97de-ab6d16b3f929.png)
 
From screenshot above we can see TOP memory consumers are tyoes from NLog.
Observations:
Unlimited constant memory grow happen only with our only app that sends highest number of messages per second. 
Problem occurs only when we enable Graylog target (inherited from TargetWithContext).
The same set of messages we duplicate (send) also to Syslog : TargetWithLayout.
But it does not create a problem when Graylog is disabled.
Memory leak occurs only when both enabled. 

**NLog version**: 4.6.8 (latest stable)

**Platform**: .Net 4.6.1 

**Current NLog config** 
![image](https://user-images.githubusercontent.com/16491966/75157820-9729f980-571d-11ea-8755-2e21e3dfda00.png)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="false"
      keepVariablesOnReload="true">
  <extensions>
    <add assembly="NLog.Targets.Syslog" />
    <!-- Required for Nlog to know where to load target from -->
    <add assembly="Lionbridge.Graylog.Nlog"/>
    <add assembly="Microsoft.ApplicationInsights.NLogTarget" />
  </extensions>

  <targets>
    <target xsi:type="AsyncWrapper"
        name="PapertrailWrapped"
        timeToSleepBetweenBatches="0"
        overflowAction="Grow">
      <target type="Syslog" name="syslog" syslogserver="value_hidden" port="value_hidden" 
              layout="${longdate}|${level:uppercase=true:padding=-5}|${logger}.${message}${onexception:${newline}Exception\: ${exception:format=tostring}}${newline}" 
              facility="Local7" machinename="${var:PapertrailMachineName:default=VoxLeonis}" sender="SER"/>
    </target>
    <target xsi:type="AsyncWrapper"
        name="GraylogWrapped"
        timeToSleepBetweenBatches="0"
        overflowAction="Grow">
      <target name="GrayLog"
              layout="${longdate}|${logger}.${message}"
              xsi:type="GraylogHttp"
              facility="Services"
              graylogServer="value_hidden"
              graylogPort="value_hidden"
              graylogAuthScheme="Basic"
              graylogAuthSecret="value_hidden"
              includeEventProperties="True">
      </target>
    </target>
    <target xsi:type="AsyncWrapper"
        name="ApplicationInsightsWrapped"
        timeToSleepBetweenBatches="0"
        overflowAction="Grow">
      <target type="ApplicationInsightsTarget" name="aiTarget" layout="${time}${logger}.${message}${onexception:${newline}Exception\: ${exception:format=tostring}}${newline}" />
    </target>
  </targets>
  <rules>
    <logger name="_*" minlevel="Trace" writeTo="PapertrailWrapped" />
    <logger name="_*" minlevel="Trace" appendTo="GraylogWrapped"/>
    <logger name="_*" minlevel="Trace" writeTo="ApplicationInsightsWrapped" />
  </rules>
</nlog>
```

Workarounds I tried:
According to recommendations in similar issues here, I tried:
1. Tried to replace:
overflowAction="Grow" with overflowAction="Block"
2. Remove  
layout="${longdate}|${logger}.${message}"
from Graylog target.
3. Updated NLog from 4.6.8 to newest 4.7.0-rc1 
At first glance, it seems it didn't help (according to observations on staging)... 

Later on I'll collect and attach metrics and memory dump from production, after above 3 applied 
(it still not released on production).

It is interesting what is root cause of problem and where it is in source code, not only workarounds to fix it.

**Comment by snakefoot** [comment]
NLog v6 extends [NLog.Targets.Network](https://www.nuget.org/packages/NLog.Targets.Network#readme-body-tab) with dedicated targets:

- [NLog Wiki - Syslog Target](https://github.com/NLog/NLog/wiki/Syslog-target)
- [NLog Wiki - Gelf Target](https://github.com/NLog/NLog/wiki/Gelf-target)
- [NLog Wiki - Splunk Target](https://github.com/NLog/NLog/wiki/Splunk-target)
- [NLog Wiki - Log4JXml Target](https://github.com/NLog/NLog/wiki/Log4JXml-target)

All of them build on top of NLog NetworkTarget with its connection-handling and buffer-reuse.

See also [NLog v6 Release Notes](https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html)
