### ISSUE TITLE
HttpNetworkSender TCP Connection Issue

### ISSUE THREAD

**Issue by amitojkapoor** [NLog/NLog.Targets.Network#8]
In `HttpNetworkSender.cs`, is there any reason why `HttpWebRequest` is used over a static `HttpClient`?

As far as I know, `HttpClient` is much more performant than `HttpWebRequest`, which is only being kept around for compatibility reasons.

The reason I am asking is because in an Azure Functions app where NLog is used to log to Loggly, I have noticed some issues. When logging is turned on, the app starts using thousands of TCP connections causing it to shutdown. Without logging, there are no issues.

Furthermore, if I use the [NLog.Targets.Loggly extension](https://github.com/neutmute/nlog-targets-loggly), I see no TCP connection issues because it uses a static `HttpClient`. While using this instead of the `Network Target` is a solution, it would be great if an extension wasn't needed because it has other different issues.

 I have deployed a custom Azure Functions app where I can input an integer and that many log statements will be logged through the `Network Target`. I have reproduced the issue this way.

**Comment by snakefoot** [comment]
[NLog.Targets.HttpClient](https://www.nuget.org/packages/NLog.Targets.HttpClient#readme-body-tab) as been released, that should improve the HttpClient-connection-handling.
